version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./DNX.ProductDetail.API.sln && dotnet publish ./DNX.ProductDetail.API.sln -c Release -o ./obj/Docker/publish"
